### PR TITLE
Linting in Python

### PR DESCRIPTION
**Pull request by schote**
- Poetry for package managing
- Configuration of linters in pyproject.toml
- Update pipeline to run all linters (use poetry script function?)
- Pass all linter checks

### CODE REVIEW

**Comment by schote** [comment]
How should we handle CI? 

- One action per manager or single action for all?
- Run linter seperately or all at once in a single command?

**Comment by chdinh** [comment]
yes, agree an overall run needs to be present as well

**Comment by schote** [comment]
Update:

- Implemented [Poe the Poet](https://poethepoet.natn.io) as a poetry plugin to run several tasks by a single command (here linting).
- Fixed linter issues.
- Created a new workflow (static-tests), which performs the static testing per service
- Merged new workflow from main to run the static-tests workflow

The static-tests GitHub workflow requires the implementation of a job per microservice. For now only the exam-manager job is implemented. Jobs for the other services can easily be derived, job title, name and working directory must be adapted. Maybe something like a loop or template can be applied to save redundancy in the GitHub workflow file. All linter tasks are run by `poetry run poe lint`. See `pyproject.toml` file for the definition of linting tasks. The same command can be used _offline_ to check linter findings.

**Comment by schote** [comment]
Update: All linter tests are up and running by a single command `poetry run poe lint`.
Use the same command to execute the tests locally: Create a virtual environment, `cd` into service, run `poetry install`, execute `poetry run poe lint`.

The static-tests action contains a lot of overhead. We should think about how we can reduce it by something like a job template. Any ideas? Also, with the current situation a new service, e.g. a new reco-service, needs to be added manually to the git-hub action.

**Review by schote — COMMENTED** [review]
Linting successfully established

**Pull request merged**
